### PR TITLE
Initial GUI, screen switch, and user information logging without CA

### PR DESCRIPTION
**Pull request by amcwong**
I implemented the use cases for switch and user information logging. The framework for the FileUserDAO, ViewManagerModel, ViewModel, main, and MainAppView have been set up. 

ViewManager model is used to switch between views. 
The main file is where the current views, use case interactors, and FileUserDAO are instantiated. 
Initial helper functions in MainView may be switched to be more CA friendly later.

Currently, there are few comments and no Java Doc use. 

Note: Credits to Benji for the DAO work.

### CODE REVIEW

**Review by sarahdingg — APPROVED** [review]
looks good

**Comment by BF20** [comment]
Seems fine

**Comment by amcwong** [comment]
Note: Credits to Benji for the DAO work!

**Review by BF20 — APPROVED** [review]

**Review by yiwxng — APPROVED** [review]
still need to implement it in CA, but thank you for implemented all this

**Pull request merged**
