### PR TITLE
Full CA Implementation for log habit

### PR DESCRIPTION
**Pull request by amcwong**
Full CA Implementation for log habit

### CODE REVIEW

**Review by BasedBerry — APPROVED** [review]
W

**Review by BF20 — APPROVED** [review]
looks good

**Review by sarahdingg — APPROVED** [review]
Goodjob finishing the full implementation!

**Review by yiwxng — APPROVED** [review]
the code is well-documented with clear Javadoc comments, and the naming conventions enhance readability. However, the logHabit method contains a try-catch block without any operations that could throw an exception. Suggestion that there should some unit tests provided, which is needed in ensuring the property changes within the view model. it may be a good idea to adhere more closely to Clean Architecture by keeping business logic out of the view model. Lastly, the pull request should be a bit more clear with description

**Pull request merged**
